# -*- coding: utf-8 -*-
"""30jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZKNXo-A7xPzxghhHZbF54zh3hW45jReh
"""



"""1.Number of occurrence
Problem statement
You have been given a sorted array/list of integers 'arr' of size 'n' and an integer 'x'.
Find the total number of occurrences of 'x' in the array/list.
Example:
Input: 'n' = 7, 'x' = 3
'arr' = [1, 1, 1, 2, 2, 3, 3]
Output: 2
"""

#use Dict
n= int(input("Enter value of n :"))

list1 = []
if n > 0:
 print("Enter  Elements :")

 for i in range(n):
    list1.append(int(input()))


else :
 exit()

x = int(input("Enter Value of x :"))


dict1 = {}

for item in list1:
    dict1[item] = dict1.get(item,0) + 1


ans = dict1.get(x, -1 )
if ans == -1 :
 print("Element not exists")
else :
 print(f"Element {x} occurs {ans} times")

#Approach 2
n= int(input("Enter value of n :"))

list1 = []
if n > 0:
 print("Enter  Elements :")

 for i in range(n):
    list1.append(int(input()))


else :
 exit()

x = int(input("Enter Value of x :"))
count =0

for item  in list1:
    if item == x :
      count += 1

if count == 0 :
 print("Element not exists")
else :
 print(f"Element {x} exists {count} times")







"""3.Find Duplicates In Array
Problem statement
You are given an array/list 'ARR' consisting of N integers, which contains elements only in the range 0 to N - 1. Some of the elements may be repeated in 'ARR'. Your task is to find all such duplicate elements.

Note:
1. All the elements are in the range 0 to N - 1.
2. The elements may not be in sorted order.
3. You can return the duplicate elements in any order.
4. If there are no duplicates present then return an empty array.

"""

#using Dict

n= int(input("Enter value of n :"))

list1 = []
if n > 0:
 print("Enter  Elements  only in Range of 0 to N-1:")

 for i in range(n):
    list1.append(int(input()))


else :
 exit()


for item in list1:
    list1[item % n] = list1[item %n ] + n



duplicate_ele = []
ele_absent = []
for i  in range(len(list1)):
    if  list1[i] // n == 2 :
     duplicate_ele.append(i)
    elif ( list1[i] // n == 0) :
     ele_absent.append(i)

print("Duplicate elements are :- ")
print(duplicate_ele)

print("Absent Elements are: -")
print(ele_absent)



"""
4.Sort 0 1 2
Problem statement
You have been given an integer array/list(ARR) of size 'N'. It only contains 0s, 1s and 2s. Write a solution to sort this array/list.

Note :
without using any inbuilt function
Try to solve the problem in 'Single Scan'. ' Single Scan' refers to iterating over the array/list just once or to put it in other words, you will be visiting each element in the array/list just once.

"""

n= int(input("Enter value of n :"))

list1 = []
if n > 0:
 print("Enter  Binary  Elements  :")

 for i in range(n):
    list1.append(int(input()))


else :
 exit()


curr = 0
l  =  len(list1)
z_index = 0
two_index = l-1

while  curr < two_index:
   if list1[curr] == 0 :
       list1[curr],list1[z_index] = list1[z_index], list1[curr]
       z_index += 1
       curr += 1
   elif list1[curr] == 2 :
        list1[curr],list1[two_index] = list1[two_index], list1[curr]
        two_index -= 1
   else :

      curr += 1



print(list1)



